"""Shared Magic Set Editor configuration loaded from the repository's .env file."""

from __future__ import annotations

import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

REPO_ROOT = Path(__file__).resolve().parent
DEFAULT_ENV_PATH = REPO_ROOT / ".env"
REQUIRED_ENV_KEYS = (
    "MSE_ROOT",
    "MSE_EXECUTABLE",
    "MSE_DATA_DIR",
    "MSE_FONTS_DIR",
    "MSE_PROJECTS_DIR",
)


def load_env_file(env_path: Path = DEFAULT_ENV_PATH) -> dict[str, str]:
    """Read the small dotenv subset emitted by :func:`write_env_file`."""
    if not env_path.is_file():
        return {}

    values: dict[str, str] = {}
    for line_number, raw_line in enumerate(env_path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].lstrip()
        if "=" not in line:
            raise RuntimeError(f"Invalid .env entry at {env_path}:{line_number}")
        key, raw_value = line.split("=", 1)
        key = key.strip()
        raw_value = raw_value.strip()
        if raw_value.startswith('"'):
            try:
                value = json.loads(raw_value)
            except json.JSONDecodeError as exc:
                raise RuntimeError(f"Invalid quoted value at {env_path}:{line_number}") from exc
        elif raw_value.startswith("'") and raw_value.endswith("'"):
            value = raw_value[1:-1]
        else:
            value = raw_value.split(" #", 1)[0].rstrip()
        values[key] = value
    return values


def write_env_file(env_path: Path, values: Mapping[str, str]) -> None:
    """Atomically write portable, quoted dotenv values."""
    env_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by setup_mse.py. Run that script again after moving MSE.",
        *(f"{key}={json.dumps(str(value))}" for key, value in values.items()),
        "",
    ]
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=env_path.parent,
            prefix=f"{env_path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary_file:
            temporary_file.write("\n".join(lines))
            temporary_path = Path(temporary_file.name)
        temporary_path.replace(env_path)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


@dataclass(frozen=True)
class MSEConfig:
    root: Path
    executable: Path
    cli: Path
    data_dir: Path
    fonts_dir: Path
    projects_dir: Path

    @classmethod
    def from_values(cls, values: Mapping[str, str]) -> "MSEConfig":
        missing = [key for key in REQUIRED_ENV_KEYS if not values.get(key)]
        if missing:
            keys = ", ".join(missing)
            raise RuntimeError(
                f"Missing MSE configuration ({keys}). Run `python setup_mse.py` first."
            )
        executable = Path(values["MSE_EXECUTABLE"]).expanduser()
        return cls(
            root=Path(values["MSE_ROOT"]).expanduser(),
            executable=executable,
            cli=Path(values.get("MSE_CLI", str(executable))).expanduser(),
            data_dir=Path(values["MSE_DATA_DIR"]).expanduser(),
            fonts_dir=Path(values["MSE_FONTS_DIR"]).expanduser(),
            projects_dir=Path(values["MSE_PROJECTS_DIR"]).expanduser(),
        )

    @classmethod
    def load(cls, env_path: Path = DEFAULT_ENV_PATH) -> "MSEConfig":
        values = load_env_file(env_path)
        # Explicit process environment values are useful in CI and override .env.
        values.update({key: os.environ[key] for key in (*REQUIRED_ENV_KEYS, "MSE_CLI") if key in os.environ})
        return cls.from_values(values)
